apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-w2s-nl
  namespace: argocd
spec:
  secretName: k8s-w2s-nl-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "k8s.w2s.nl"
    - "*.k8s.w2s.nl"
